name: Code check
on:
  pull_request:
  push:
      branches:
        - main
jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/dev.txt --upgrade pip
      - name: Run codecheck
        run: bash scripts/codecheck.sh
      - name: Run tests
        run: bash -x scripts/run_tests.sh
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.5
        with:
          reports: "reports/coverage.xml"
          targetdir: 'coveragereport'
          reporttypes: MarkdownSummaryGithub
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport
      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        run: gh pr comment $PR_NUMBER --body-file coveragereport/SummaryGithub.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Publish coverage in build summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'reports/junit.xml'
          check_name: tests
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
